### ISSUE TITLE
该插件无法在官方master分支下使用！

### ISSUE THREAD

**Issue by zxlhhyccc** [sirpdboy/luci-app-chatgpt#1]
![image](https://github.com/sirpdboy/chatgpt-web/assets/45259624/996b5554-4532-493b-b1e8-5c9ab324e72b)

**将`fs`改为`nixio.fs`后：**
![image](https://github.com/sirpdboy/chatgpt-web/assets/45259624/ad6ade4b-d704-41b9-995d-54f91aa8e1f7)

**Comment by sirpdboy** [comment]
进行了修复，你现试试哦。

**Comment by zxlhhyccc** [comment]
最新版本在官方master分支下现在出现这个报错：
![image](https://github.com/sirpdboy/chatgpt-web/assets/45259624/da56936c-beb4-4492-bb4c-3b6b60563425)

**Comment by sirpdboy** [comment]
这个cbi的问题，已经查出来，是openwrt传输参数错误报错，新版本已经解决。

**Comment by jxltom** [comment]
可以更新一下ipk吗 @sirpdboy
