### ISSUE TITLE
最新1.13版本在官方master分支下现在出现这个报错！

### ISSUE THREAD

**Issue by zxlhhyccc** [sirpdboy/luci-app-chatgpt#2]
![image](https://github.com/sirpdboy/chatgpt-web/assets/45259624/66bbc9c1-e0c8-42f4-9eec-c27631984791)

**Comment by sirpdboy** [comment]
是没有CBI  。 没用官网的编译。。官网的兼容这么差了吗？

**Comment by zxlhhyccc** [comment]
官方不应该没有CBI吧，我认为是htm里要有相关代码。。。。

**Comment by sirpdboy** [comment]
用了cbi方案，你再试试

**Comment by zxlhhyccc** [comment]
> 用了cbi方案，你再试试

测试了一下，还是同样的问题。。。

![image](https://github.com/sirpdboy/chatgpt-web/assets/45259624/02f3a078-a473-41d2-a7ee-474da7f7df40)

**Comment by sirpdboy** [comment]
这个cbi的问题，已经查出来，是openwrt传输参数错误报错，新版本已经解决。

**Comment by ShuJz** [comment]
@sirpdboy 新版本可以再发布一个release吗？感谢，现在最新的release还会有这个问题。
